services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: rentify
      POSTGRES_PASSWORD: rentify123
      POSTGRES_DB: rentifydb
    ports:
      - "5433:5432"  # Change the host port to 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
